sonar.projectKey=Pern-Store
sonar.projectName=Pern-Store
sonar.projectVersion=1.0
sonar.sources=./client
sonar.sourceEncoding=UTF-8
sonar.host.url=${env.SONAR_HOST_URL}
sonar.login=${env.SONAR_TOKEN}
# Exclude non-Node.js files, such as tests, build directories, node_modules, CSS, HTML, etc.
sonar.exclusions=**/node_modules/**,**/test/**
# Enable JavaScript analysis (for Node.js)
sonar.language=js  # or 'ts' for TypeScript projects

sonar.javascript.lcov.reportPaths=coverage/lcov.info